version: '2'
services:
  reacttestcnt-postgresql:
    image: postgres:12.1
    # volumes:
    #     - ~/volumes/jhipster/reacttestcnt/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=reacttestcnt
      - POSTGRES_PASSWORD=
    ports:
      - 5432:5432
